source:
  host: "localhost"
  port: "5432"
  user: "postgres"
  pass: "password"
  db: "tfmv"
  isUnixSocket: false

target:
  host: "localhost"
  port: "5432"
  user: "postgres"
  pass: "password"
  db: "tfmv"
  isUnixSocket: false

tables:
  - "customer"
  - "tommy"
  - "barb"
